import { c as create_ssr_component, d as add_attribute, e as escape } from "../../chunks/ssr.js";
const AmptLogo = "/_app/immutable/assets/ampt.661ce4a9.svg";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: "@import url('https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap');@import url('https://fonts.googleapis.com/css?family=Source+Code+Pro:400,700&display=swap');h5.svelte-sc3uo4{font-family:'Montserrat', sans-serif;font-weight:400;font-size:1.5rem;color:#fff;text-align:center;margin:0;padding:0}a.svelte-sc3uo4{color:#fff;text-decoration:none;border-bottom:2px solid #fff;transition:border-bottom-color 0.2s ease-in-out}a.svelte-sc3uo4:hover{border-bottom-color:#f00}p5.svelte-sc3uo4{font-family:'Montserrat', sans-serif;font-weight:400;font-size:1rem;color:#fff;text-align:center;margin:0;padding:0}body.svelte-sc3uo4{margin:0;padding:0;font-family:sans-serif;background:#000}.spacing.svelte-sc3uo4{margin:10px}.code.svelte-sc3uo4{font-family:'Source Code Pro', monospace;font-weight:400;font-size:1rem;color:#fff;text-align:center;margin:0;border-radius:10px;padding:5px;background-color:#333;display:inline-block}.column.svelte-sc3uo4{display:flex;flex-direction:column;justify-content:center;align-content:center}.circle.svelte-sc3uo4{border-radius:50%;background-color:#fff;padding:30px;margin:20px;align-self:center;display:flex;align-content:center;justify-content:center;width:20;height:20;box-shadow:0 0 20px rgba(0, 0, 0, 0.5)}.container.svelte-sc3uo4{display:flex;flex-direction:column;justify-content:center;align-content:center;background:linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);background-size:400% 400%;animation:svelte-sc3uo4-gradient 15s ease infinite;height:100vh;width:100vw;overflow:hidden}@keyframes svelte-sc3uo4-gradient{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { data } = $$props;
  let { url = data.url } = $$props;
  if ($$props.data === void 0 && $$bindings.data && data !== void 0)
    $$bindings.data(data);
  if ($$props.url === void 0 && $$bindings.url && url !== void 0)
    $$bindings.url(url);
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-1h7xc01_START -->${$$result.title = `<title>Ampt + Svelte</title>`, ""}<meta name="description" content="Ampt + Svelte Demo App"><!-- HEAD_svelte-1h7xc01_END -->`, ""} <body class="svelte-sc3uo4"><div class="container svelte-sc3uo4"><div class="column svelte-sc3uo4"><div class="circle svelte-sc3uo4" data-svelte-h="svelte-1iig3jj"><img style="align-self: center;"${add_attribute("src", AmptLogo, 0)} alt="Ampt Logo" width="150" height="150"></div> <h5 class="svelte-sc3uo4" data-svelte-h="svelte-16vt04c">Welcome to Svelte on Ampt!</h5> <div class="spacing svelte-sc3uo4"></div> <p5 class="svelte-sc3uo4" data-svelte-h="svelte-14sjecb">Run <p5 class="code svelte-sc3uo4">ampt dev</p5> to start the development server</p5> <p5 style="margin-bottom: 10px;" class="svelte-sc3uo4" data-svelte-h="svelte-pfbksc">Edit this page by modifying <p5 class="code svelte-sc3uo4">src/routes/+page.svelte</p5></p5> <p5 class="svelte-sc3uo4" data-svelte-h="svelte-1glh2p9">Load server side data by modifying<p5 class="code svelte-sc3uo4">src/routes/+page.ts</p5> and <p5 class="code svelte-sc3uo4">src/routes/+page.server.ts</p5></p5> <div class="spacing svelte-sc3uo4"></div> <p5 class="svelte-sc3uo4">Deploy your changes by running <p5 class="code svelte-sc3uo4" data-svelte-h="svelte-oc2dp8">build</p5> in the Ampt shell to see your changes at your sandbox url: <a${add_attribute("href", url, 0)} class="svelte-sc3uo4">${escape(url)}</a></p5> <div class="spacing svelte-sc3uo4"></div> <p5 class="svelte-sc3uo4" data-svelte-h="svelte-1fxm64s">Run<p5 class="code svelte-sc3uo4">ampt deploy</p5> to deploy to a stage environment</p5> <div class="spacing svelte-sc3uo4"></div> <p5 style="margin-bottom: 5px;" class="svelte-sc3uo4" data-svelte-h="svelte-1r95xme">Learn more about Ampt by checking out our <a href="https://getampt.com/docs" target="_blank" class="svelte-sc3uo4">docs</a></p5> <p5 class="svelte-sc3uo4" data-svelte-h="svelte-1wbw6ua">Learn more about Svelte by checking out their <a href="https://svelte.dev/docs" target="_blank" class="svelte-sc3uo4">docs</a></p5></div></div> </body>`;
});
export {
  Page as default
};
